# Generated by Django 5.2.7 on 2025-10-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(default='', verbose_name='Описание'),
        ),
    ]
