# Generated by Django 5.2.7 on 2025-10-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
