# Generated by Django 5.2.7 on 2025-10-23 16:49

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='long_desc',
            field=CKEditor5Field(blank=True, verbose_name="Описание", config_name="default"),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('place', 'order'), name='unique_order_per_place'),
        ),
    ]
