# Generated by Django 5.2.7 on 2025-10-23 17:23

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_place_long_desc_photo_unique_order_per_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='long_desc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Полное описание'),
        ),
    ]
